# This is a basic workflow to help you get started with Actions

name: README.md to PDF (on push)

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main
    paths:
      - 'README.md'
      - 'img/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkoutConvertMdToPdfPush:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Converts 
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: .
          image_import: /img
      # Commit and push
      - uses: EndBug/add-and-commit@v7.1.1
        with:
          message: 'adds/updates the auto generated README.pdf'
